

info:
  namespace: radio

items:
  radio_czerwoni_0:
    display_name: "&fRadio: &cCzerwonych"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby nadawać.'
      - '&7Trzymaj na hotbarze, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_czerwoni_0
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false
  radio_czerwoni_1:
    display_name: "&fRadio: &cCzerwonych"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby nadawać.'
      - '&7Trzymaj na hotbarze, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_czerwoni_1
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false
  radio_czerwoni_2:
    display_name: "&fRadio: &cCzerwonych"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby nadawać.'
      - '&7Trzymaj na hotbarze, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_czerwoni_2
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false

  radio_niebiescy_0:
    display_name: "&fRadio: &bNiebieskich"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby nadawać.'
      - '&7Trzymaj na hotbarze, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_niebiescy_0
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false
  radio_niebiescy_1:
    display_name: "&fRadio: &bNiebieskich"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby nadawać.'
      - '&7Trzymaj na hotbarze, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_niebiescy_1
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false
  radio_niebiescy_2:
    display_name: "&fRadio: &bNiebieskich"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby nadawać.'
      - '&7Trzymaj na hotbarze, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_niebiescy_2
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false

  radio_handlarze_0:
    display_name: "&fRadio: &eHandlarzy"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby nadawać.'
      - '&7Trzymaj na hotbarze, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_handlarze_0
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false
  radio_handlarze_1:
    display_name: "&fRadio: &eHandlarzy"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby nadawać.'
      - '&7Trzymaj na hotbarze, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_handlarze_1
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false
  radio_handlarze_2:
    display_name: "&fRadio: &eHandlarzy"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby nadawać.'
      - '&7Trzymaj na hotbarze, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_handlarze_2
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false

  radio_piraci_0:
    display_name: "&fRadio: &aPiratów"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby nadawać.'
      - '&7Trzymaj na hotbarze, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_piraci_0
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false
  radio_piraci_1:
    display_name: "&fRadio: &aPiratów"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby nadawać.'
      - '&7Trzymaj na hotbarze, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_piraci_1
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false
  radio_piraci_2:
    display_name: "&fRadio: &aPiratów"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby nadawać.'
      - '&7Trzymaj na hotbarze, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_piraci_2
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false

  radio_streamcraft_0:
    display_name: "&fRadio: &dStreamCraft"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby nadawać.'
      - '&7Trzymaj na hotbarze, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_streamcraft_0
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false
  radio_streamcraft_1:
    display_name: "&fRadio: &dStreamCraft"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby nadawać.'
      - '&7Trzymaj na hotbarze, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_streamcraft_1
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false
  radio_streamcraft_2:
    display_name: "&fRadio: &dStreamCraft"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby nadawać.'
      - '&7Trzymaj na hotbarze, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_streamcraft_2
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false

  radio_piraci_random_0:
    display_name: "&fStare Radio: Piratów"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_piraci_random_0
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false
  radio_piraci_random_1:
    display_name: "&fStare Radio: Piratów"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_piraci_random_1
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false
  radio_piraci_random_2:
    display_name: "&fStare Radio: Piratów"
    category: "radios"
    lore:
      - '&7Trzymaj w głównej ręce, aby słuchać.'
    resource:
      material: SHEARS
      generate: false
      model_path: item/radio_piraci_random_2
    stack_size: 1
    durability:
      max_durability: 100
      durability: 100
      disappear_when_broken: true
      unbreakable: false

recipes:
  crafting_table:
    radio_czerwoni_0:
      permission: "radio.craft.czerwoni"
      enabled: true
      pattern:
        - XXI
        - XWI
        - XJI
      pattern_2:
        - XIX
        - WIX
        - JIX
      ingredients:
        I: IRON_BLOCK
        J: JUKEBOX
        W: RED_WOOL
      result:
        item: radio:radio_czerwoni_0
        amount: 1
    radio_niebiescy_0:
      permission: "radio.craft.niebiescy"
      enabled: true
      pattern:
        - XXI
        - XWI
        - XJI
      pattern_2:
        - XIX
        - WIX
        - JIX
      ingredients:
        I: IRON_BLOCK
        J: JUKEBOX
        W: LIGHT_BLUE_WOOL
      result:
        item: radio:radio_niebiescy_0
        amount: 1
    radio_handlarze_0:
      permission: "radio.craft.handlarze"
      enabled: true
      pattern:
        - XXI
        - XWI
        - XJI
      pattern_2:
        - XIX
        - WIX
        - JIX
      ingredients:
        I: IRON_BLOCK
        J: JUKEBOX
        W: YELLOW_WOOL
      result:
        item: radio:radio_handlarze_0
        amount: 1
    radio_piraci_0:
      permission: "radio.craft.piraci"
      enabled: true
      pattern:
        - XXI
        - XWI
        - XJI
      pattern_2:
        - XIX
        - WIX
        - JIX
      ingredients:
        I: IRON_BLOCK
        J: JUKEBOX
        W: LIME_WOOL
      result:
        item: radio:radio_piraci_0
        amount: 1
    radio_streamcraft_0:
      permission: "radio.craft.streamcraft"
      enabled: true
      pattern:
        - XXI
        - XWI
        - XJI
      pattern_2:
        - XIX
        - WIX
        - JIX
      ingredients:
        I: IRON_BLOCK
        J: JUKEBOX
        W: MAGENTA_WOOL
      result:
        item: radio:radio_streamcraft_0
        amount: 1
    radio_piraci_random_0:
      permission: "radio.craft.randomchannel.piraci"
      enabled: true
      pattern:
        - XXI
        - XWI
        - XJI
      pattern_2:
        - XIX
        - WIX
        - JIX
      ingredients:
        I: IRON_BLOCK
        J: JUKEBOX
        W: WHITE_WOOL
      result:
        item: radio:radio_piraci_random_0
        amount: 1